[build]
publish = "public"
command = "./mvnw install"

[context.production.environment]
port = 8080
[context.deploy-preview]
port = 8080

[context.deploy-preview.environment]
port = 8080

[context.branch-deploy]
port = 8080

[context.branch-deploy.environment]
port = 8080
